package se.miun.kran1800.dt031g.bathingsites;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "bathing_site",
        primaryKeys = {"id"})
public class BathingSite {
    @PrimaryKey(autoGenerate = true)
    public int id;
    public String name;
    public String description;
    public String address;
    public double latitude;
    public double longitude;
    public int grade;
    public double waterTemp;
    public String dateForTemp;

    // TODO: Check if variables can be private

    // A bathing site object, primary key is autogenerated id.
    public BathingSite(int id, String name, String description, String address,
                       double latitude, double longitude, int grade,
                        double waterTemp, String dateForTemp) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.address = address;
        this.latitude = latitude;
        this.longitude = longitude;
        this.grade = grade;
        this.waterTemp = waterTemp;
        this.dateForTemp = dateForTemp;
    }
}
